
title: 
firstname: Christiane
lastname: Elgert
year: 2024
email: christiane.elgert@gmail.com
description: "Mathematician with over ten years of research experience. Applied my strong analytical background to address complex bioinformatics challenges, 
culminating in the successful completion of five projects in phylogenetics and molecular evolution. Demonstrated expertise in developing 
innovative methods and tools for advanced data analysis. Highly motivated, emphatic, communicative and solution-oriented personality
who is used to work efficiently in an international, interdisciplinary and supporting team atmosphere."
keywords: "Wissbegier, Mathematik, Mathematiker, Bioinformatik, Bioinformatiker, Bücher, Wissen, Lesen, Genetik, Phylogenie, Kommunikation, Selbstausdruck, Sport, Gesundheit, Gewichtheben, Krafttraining, Interdisziplinär, Interdisziplinarität, Innovation, Innovationen, Kreativität, Kreativ, Forschung, Forschungen, TechnischesFachwissen,Technische Expertise, Leidenschaft, Leidenschaftlich, Perspektive, Perspektiven, Grenzen, Grenzüberschreitend, Inspiration, Inspirierend, Faszinierend, Faszination, HTML, CSS, JavaScript, 
LifeScience, Curiosity, Mathematics, Mathematician, Bioinformatics, Bioinformatician, Books, Knowledge, Reading, Genetics, Phylogeny, Communication, Self-expression, Sports, Health, Weightlifting, Strength training, Interdisciplinary, Interdisciplinarity, Innovation, Innovations, Creativity, Creative, Research, Researches, Technical expertise, Technical knowledge, Passion, Passionate, Perspective, Perspectives, Boundaries, Boundary-crossing, Inspiration, Inspiring, Fascinating, Fascination"
baseurl: ""
url: "https://elli-ellgard.github.io/index.html" 
linkedin: christiane-elgert
github:  Elli-ellgard

# Build settings
theme: minima
#plugins:
# - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
